DROP TABLE exemplo1.VISITED
DROP TABLE exemplo1.TAKING
DROP TABLE exemplo1.SCHEDULE
DROP TABLE exemplo1.RECEIVED
DROP TABLE exemplo1.NOT_FAMILY
DROP TABLE exemplo1.LEAVES
DROP TABLE exemplo1.VISIT
DROP TABLE exemplo1.exits
DROP TABLE exemplo1.ACCOMPANIED
DROP TABLE exemplo1.appointment
DROP TABLE exemplo1.medicine
DROP TABLE exemplo1.doctor
DROP TABLE exemplo1.diagnosed
DROP TABLE exemplo1.DEPENDENT
DROP TABLE exemplo1.family
DROP TABLE exemplo1.visitor
DROP TABLE exemplo1.patient
DROP TABLE exemplo1.disease
DROP TABLE exemplo1.bed
DROP TABLE exemplo1.bedroom